config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#profile'
  resources :users, only: %i[profile]
  resources :accounts, only: %i[show create destroy]
  concern :operational do
    member { get :show }
    collection { post :create }
  end

  resources :bets, except: %i[show create index destroy new update edit], concerns: :operational
  resources :transfers, except: %i[show create index destroy new update edit], concerns: :operational

  get 'search_data', to: 'bets#search_data'
end

app/models/account.rb
class Account < ApplicationRecord
  DEFAULT_BALANCE = 0
  before_validation :set_default_attributes, on: :create

  has_many :operations, dependent: :destroy
  belongs_to :bookmaker
  belongs_to :user

  validates :number, :balance, :bookmaker, presence: true
  validates :number, uniqueness: { case_sensitive: false }

  def balance_history
    Account::BalanceHistoryService.call(operations).history
  end

  private

  def set_default_attributes
    self.number = SecureRandom.hex(10)
    self.balance = DEFAULT_BALANCE if balance.nil? || balance.zero?
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :account, only: %i[show destroy]
  before_action :teams, :games, only: :show

  def show
    @operations = @account.operations.includes(:operational).order(created_at: :desc).limit(5)
  end

  def create
    account = current_user.accounts.new(account_params)
    if account.save
      redirect_to root_path, notice: 'Your account successfully created.'
    else
      render root_path
    end
  end

  def destroy
    if @account.destroy
      redirect_to root_path, notice: 'Your account successfully deleted.'
    else
      render root_path
    end
  end

  private

  def teams
    @teams ||= Team.all
  end

  def games
    @games ||= Game.includes(%i[home_team away_team]).coming.order(date: :asc)
  end

  def account
    @account ||= Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:bookmaker_id)
  end
end

app/views/accounts/_account.html.slim
.container-sm
  .row
    .col-md
      = link_to account.bookmaker.name, account_path(account)
    .col-sm
      = link_to 'Delete', account_path(account), method: :delete, data: {confirm: 'Delete account?'}

app/views/accounts/_form.html.slim
.new_account_form
  p New account
  = form_for Account.new, remote: true  do |f|
    = f.label :bookmaker, 'Choose bookmaker'
    = f.collection_select :bookmaker_id, Bookmaker.all, :id, :name
    = f.submit 'Save'

app/views/accounts/accounts.js.erb
let new_account_form_button = document.querySelector('.new_account_button');
let new_account_form = document.querySelector('.new_account');
new_account_form_button.addEventListener('click', (e) => {
    console.log('h')
    if(new_account_form.style.display === 'none') {
        console.log('b')
        new_account_form.style.display = ''
    } else {
        console.log('y')
        new_account_form.style.display = 'none'
    }
});

app/views/accounts/show.html.slim
= "Bookmaker: #{@account.bookmaker.name}"
= "Balance: #{@account.balance}"

.row
  .col-6
    .operations
      table.table-striped
        caption Accounts Operations
        tr
          th Operational ID
          th Operational Type
          th Created At
          th Account Bookmaker
          = render @operations
  .col-6
    = render 'transfers/new'
  .col-6
    = line_chart @account.balance_history
  .col-6
    - unless @games.blank?
      = render 'bets/new'